const countriesArray = [
  {
    id: 1,
    continent: "Europe",
    country: "Turkey",
    timezone: "Europe/Istanbul",
  },
  { id: 2, continent: "Asia", country: "Japan", timezone: "Asia/Tokyo" },
  { id: 3, continent: "Asia", country: "India", timezone: "Asia/Kolkata" },
  {
    id: 4,
    continent: "Africa",
    country: "South Africa",
    timezone: "Africa/Johannesburg",
  },
  { id: 5, continent: "Africa", country: "Nigeria", timezone: "Africa/Lagos" },
  {
    id: 6,
    continent: "North America",
    country: "Canada",
    timezone: "America/Toronto",
  },
  {
    id: 7,
    continent: "North America",
    country: "Mexico",
    timezone: "America/Mexico_City",
  },
  {
    id: 8,
    continent: "South America",
    country: "Brazil",
    timezone: "America/Sao_Paulo",
  },
  {
    id: 9,
    continent: "South America",
    country: "Argentina",
    timezone: "America/Argentina/Buenos_Aires",
  },
  {
    id: 10,
    continent: "Europe",
    country: "Germany",
    timezone: "Europe/Berlin",
  },
  {
    id: 11,
    continent: "Australia/Oceania",
    country: "Australia",
    timezone: "Australia/Sydney",
  },
  {
    id: 12,
    continent: "Australia/Oceania",
    country: "New Zealand",
    timezone: "Pacific/Auckland",
  },
  {
    id: 13,
    continent: "Europe",
    country: "United Kingdom",
    timezone: "Europe/London",
  },
  {
    id: 14,
    continent: "Europe",
    country: "France",
    timezone: "Europe/Paris",
  },
  {
    id: 15,
    continent: "Europe",
    country: "Italy",
    timezone: "Europe/Rome",
  },
  {
    id: 16,
    continent: "Europe",
    country: "Spain",
    timezone: "Europe/Madrid",
  },
  {
    id: 17,
    continent: "Europe",
    country: "Netherlands",
    timezone: "Europe/Amsterdam",
  },
  {
    id: 18,
    continent: "Europe",
    country: "Sweden",
    timezone: "Europe/Stockholm",
  },
  {
    id: 19,
    continent: "Europe",
    country: "Greece",
    timezone: "Europe/Athens",
  },
  {
    id: 20,
    continent: "Europe",
    country: "Portugal",
    timezone: "Europe/Lisbon",
  },
  {
    id: 21,
    continent: "Europe",
    country: "Poland",
    timezone: "Europe/Warsaw",
  },
  {
    id: 22,
    continent: "Europe",
    country: "Ukraine",
    timezone: "Europe/Kyiv",
  },
  {
    id: 23,
    continent: "Europe",
    country: "Russia",
    timezone: "Europe/Moscow",
  },
  {
    id: 24,
    continent: "Asia",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: 25,
    continent: "Asia",
    country: "South Korea",
    timezone: "Asia/Seoul",
  },
  {
    id: 26,
    continent: "Asia",
    country: "Singapore",
    timezone: "Asia/Singapore",
  },
  {
    id: 27,
    continent: "Asia",
    country: "Thailand",
    timezone: "Asia/Bangkok",
  },
  {
    id: 28,
    continent: "Asia",
    country: "Indonesia",
    timezone: "Asia/Jakarta",
  },
  {
    id: 29,
    continent: "Asia",
    country: "Philippines",
    timezone: "Asia/Manila",
  },
  {
    id: 30,
    continent: "Asia",
    country: "United Arab Emirates",
    timezone: "Asia/Dubai",
  },
  {
    id: 31,
    continent: "Asia",
    country: "Saudi Arabia",
    timezone: "Asia/Riyadh",
  },
  {
    id: 32,
    continent: "Asia",
    country: "Israel",
    timezone: "Asia/Jerusalem",
  },
  {
    id: 33,
    continent: "Asia",
    country: "Pakistan",
    timezone: "Asia/Karachi",
  },
  {
    id: 34,
    continent: "Asia",
    country: "Vietnam",
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    id: 35,
    continent: "Africa",
    country: "Egypt",
    timezone: "Africa/Cairo",
  },
  {
    id: 36,
    continent: "Africa",
    country: "Kenya",
    timezone: "Africa/Nairobi",
  },
  {
    id: 37,
    continent: "Africa",
    country: "Morocco",
    timezone: "Africa/Casablanca",
  },
  {
    id: 38,
    continent: "Africa",
    country: "Ghana",
    timezone: "Africa/Accra",
  },
  {
    id: 39,
    continent: "Africa",
    country: "Ethiopia",
    timezone: "Africa/Addis_Ababa",
  },
  {
    id: 40,
    continent: "Africa",
    country: "Tanzania",
    timezone: "Africa/Dar_es_Salaam",
  },
  {
    id: 41,
    continent: "North America",
    country: "United States",
    timezone: "America/New_York",
  },
  {
    id: 42,
    continent: "North America",
    country: "United States West",
    timezone: "America/Los_Angeles",
  },
  {
    id: 43,
    continent: "North America",
    country: "Canada West",
    timezone: "America/Vancouver",
  },
  {
    id: 44,
    continent: "North America",
    country: "Costa Rica",
    timezone: "America/Costa_Rica",
  },
  {
    id: 45,
    continent: "North America",
    country: "Jamaica",
    timezone: "America/Jamaica",
  },
  {
    id: 46,
    continent: "South America",
    country: "Chile",
    timezone: "America/Santiago",
  },
  {
    id: 47,
    continent: "South America",
    country: "Colombia",
    timezone: "America/Bogota",
  },
  {
    id: 48,
    continent: "South America",
    country: "Peru",
    timezone: "America/Lima",
  },
  {
    id: 49,
    continent: "South America",
    country: "Uruguay",
    timezone: "America/Montevideo",
  },
  {
    id: 50,
    continent: "South America",
    country: "Venezuela",
    timezone: "America/Caracas",
  },
  {
    id: 51,
    continent: "Australia/Oceania",
    country: "Fiji",
    timezone: "Pacific/Fiji",
  },
  {
    id: 52,
    continent: "Australia/Oceania",
    country: "Papua New Guinea",
    timezone: "Pacific/Port_Moresby",
  },
  {
    id: 53,
    continent: "Australia/Oceania",
    country: "Samoa",
    timezone: "Pacific/Apia",
  },
];

export default countriesArray;



